language: node_js
node_js:
- 'node'
branches:
  only:
  - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8 
env:
- NODE_ENV=travis
- CXX=g++-4.8
services:
- postgresql
before_script:
- psql -c 'create database nitro_travis;' -U postgres