language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
services:
- redis-server
before_script:
- psql -c 'create database nitro_travis;' -U postgres
after_success:
- make coveralls
deploy:
  provider: heroku
  api_key:
    secure: GI16AYIG5XMozVTpZ2SihW8KdTVy6uCPkJiuOALPDnQA/hwoEWmhaQzW3xakDA0hMe02n539pMcFq2PvhIEkFYitduAe6TDy87/col9BRJBDagdpNAFglH4//bCG5Qh6ur0BC4zpCwMcmbQZUswXeG9EEOPNAQghvSyT8Prodp8=
  app: nitro-server
  on:
    repo: CaffeinatedCode/nitro-server
