language: node_js
node_js:
- '0.10'
services:
- mysql
before_script:
- mysql -e 'create database nitro_travis'
after_script:
- npm run-script coveralls
deploy:
  provider: heroku
  api_key:
    secure: D9RWv2y2BU55r2wJQxJIkg20OWmA+xlb2HY4gndWu9ghuZD3YRnMAQBmeaAl2sUZsLFiuMf03spPx+lEXVe7ISBy3tRmLdi5dsIxVROYYlYfaYKKR3kwoggNVmugYA9AXDPo9ioF/EAyv42T/WYweUVT4JJai0aom6R1eeVJDy8=
  app: nitro-server
  on:
    repo: stayradiated/nitro-server
