language: node_js
node_js:
- '0.10'
before_script:
- psql -c 'create database nitro_travis;' -U postgres
after_success:
- make coveralls
deploy:
  provider: heroku
  api_key:
    secure: QIWX4dxkLP2kH3XmpVIZVQTuI/LiHgpH5X0J8T+QySXINiq9XYVPF2sElGKqv1UutgJCuxhSCEtnDqQZVFJpW0dKKDv9WyrcKWsKb3tE8pBEmbaxafKTsGz+pf0zEjNm1yIomky+RqZe/TSn897nJXq8T2MXie83Hap3YIZOyZI=
  app: nitro-server
  on:
    repo: CaffeinatedCode/nitro-server
